<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>


    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>

            <div class="col-md-6 new-users">
				<div class="box-account box-account-padding box-account-top-margin">
					<h3 class="float-left newregister">New Customers</h3>

					<div class="box-content">
						<p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>

						<div class="btn-group">
							<button type="button" title="<?php echo $this->__('Create an Account') ?>" class="btn btn-primary" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
						</div>
					</div>

				</div>
			</div>

            <div class="col-md-6 registered-users">
				<div class="box-account box-account-padding box-account-top-margin">
					<h3 class="float-left loginregister"><?php echo $this->__('Registered Customers') ?></h3>
					<div class="box-content">
						<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
						<ul class="form-list">
							<li>
								<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
								<div class="input-box">
									<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
								</div>
							</li>
							<li>
								<label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
								<div class="input-box">
									<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
								</div>
							</li>
							<?php echo $this->getChildHtml('form.additional.info'); ?>
							<?php echo $this->getChildHtml('persistent.remember.me'); ?>
						</ul>
						<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
						<p class="required"><?php echo $this->__('* Required Fields') ?></p>
						<div class="btn-group">
							<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="btn btn-info"><?php echo $this->__('Forgot Your Password?') ?></a>
							<button type="submit" class="btn btn-primary f-right" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
						</div>
					</div>
                </div>
        	</div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>


