<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php

$post = $this->getPost();


//-------------------------------------------------------
//------------ Check if a contributer article ---------------------
//-------------------------------------------------------
$urlString = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($urlString);
$_contributer_article = false;
if (strpos($url->getPath(),'im-listening/contributors') == 1 )
{
	if ( in_array(7,$post->getCategoryIds()) && !strpos($url->getPath(),'all')  )
	{
		$_contributer_article = true;
	}
}
//-------------------------------------------------------
//------------ end ---------------------
//-------------------------------------------------------


?>
<?php if ($post): ?>
	<?php $helper = $this->helper('wordpress') ?>
	<?php $author = $post->getAuthor();


	$authorAvatar= $post->getAuthorAvatarUrl(50, $author->getUserEmail());


	?>
	<div class="panel panel-default">

		<div class="panel-body">

			<div class="wordpress-header">
				<div class="date-wrapper">
				<span class="date-day">
					<?php
					echo date('d', strtotime($post->getPostDateRaw()));
					?>
				</span>
				<span class="date-month-year">
					<?php
					echo date('M Y', strtotime($post->getPostDateRaw()));
					?>
				</span>
				</div>
				<div class="title-wrapper">

					<a class="h2-wordpress" href="<?php echo $_url ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
						<h2><?php echo $this->escapeHtml($post->getPostTitle()) ?></h2>
					</a>
					<div class="wordpress-contributor-wrapper">
						<?php //echo $post->getAuthor()->getContributorImage(); ?>

						<div class="contributor-wrapper">

							<?php
							if ( $post->getAuthor()->getContributorImage() != '' )
							{
								?>
								<img src="<?php echo $post->getAuthor()->getContributorImage(); ?>">
							<?php
							}
							?>
							<a href="<?php echo Mage::getBaseUrl().'im-listening/contributors/'. $post->getAuthor()->getUserNicename(); ?>/all">
								<?php echo $post->getAuthor()->getDisplayName(); ?>
								<span>View My Articles</span>
							</a>
						</div>
					</div>

					<div class="addthis_sharing_toolbox"></div>
					<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53a3aa090df647cf"></script>
				</div>
			</div>



			<div class="post-view">



				<?php echo $this->getBeforePostContentHtml() ?>
				<div class="post-entry entry std<?php if ($post->getFeaturedImage()): ?> post-entry-with-image<?php endif; ?>">


					<?php if ($post->isViewableForVisitor()): ?>

						<?php if ($featuredImage = $post->getFeaturedImage()): ?>

							<img  class="media-object featured-image-imlistening"  src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/> <br />

						<?php endif; ?>

						<?php echo $post->getPostContent() ?>

						<?php
						if ( $_contributer_article )
						{
							?>
						<div class="contributer-actions">
							<a href="<?php echo $urlString; ?>/all" class="btn btn-primary">View all my articles</a>
							</div>
						<?php
						}
						?>

					<?php else: ?>
						<?php echo $this->getPasswordProtectHtml() ?>
					<?php endif; ?>

					<p>&nbsp;</p>
					<!-- Go to www.addthis.com/dashboard to customize your tools -->
					<div class="addthis_native_toolbox"></div>
					<p>&nbsp;</p>
				</div>

				<?php //echo $this->getAfterPostContentHtml() ?>

				<?php echo $this->getCommentsHtml() ?>
			</div>
		</div>
	</div>
<?php endif; ?>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53a3aa090df647cf"></script>
