<?php
/**
 * @category    Bubble
 * @package     Bubble_CmsTree
 * @version     1.2.6
 * @copyright   Copyright (c) 2014 BubbleCode (http://www.bubbleshop.net)
 */

/**
 * @var $this Bubble_CmsTree_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('//i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <h4><?php echo $this->helper('bubble_cmstree')->__('Bubble CmsTree allows you to manage CMS pages as a tree structure.'); ?></h4>
        <p><?php echo $this->helper('bubble_cmstree')->__('Supports pages permissions, drag & drop, 301 redirects, shared pages and frontend navigation.'); ?></p>
    </div>
</div>