
<div class="box-account box-account-padding account-information">
    <h3 class="float-left"><?php echo $this->__('Edit Account Information') ?></h3>

	<div class="box-content">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" enctype="multipart/form-data" id="form-validate">
	<input type="hidden" name="edit_catch" value="1">

        <?php echo $this->getBlockHtml('formkey')?>

        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li class="fields">
				<div class="field">
					<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
					<div class="input-box">
						<input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
					</div>
				</div>
            </li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li class="fields">
				<div class="field">
					<?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
				</div>

				<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
				<?php if ($_gender->isEnabled()): ?>
					<div class="field"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></div>
				<?php endif ?>

			</li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li class="fields"><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>

            <li class="control">
				<div class="field">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
				</div>
            </li>
        </ul>
    </div>
</div>
    <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
    <?php if ($userDefinedAttributes):?>
    <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
    <?php endif;?>
<div class="box-account box-account-padding change-password">
	<h3 class="float-left"><?php echo $this->__('Change Password')?></h3>

	<div class="box-content">
			<div class="">
				<ul class="form-list">
					<li>
						<label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
						<div class="input-box">
							<input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
							<div class="input-box">
								<input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
							</div>
						</div>
						<div class="field">
							<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
							<div class="input-box">
								<input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
							</div>
						</div>
					</li>
				</ul>
			</div>
	</div>
</div>
<div class="box-account box-account-padding update-details">
	<div class="box-content">
		<div class="btn-group">
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			<a class="back-link btn btn-default" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
			<button type="submit" title="<?php echo $this->__('Save') ?>"  class="btn btn-info  float-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
		</div>
</div>
	</div>

</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(5).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(5).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>

