<?php
$_form = $this;
$_code = $_form->getMethodCode();
$_method = $_form->getMethod();
$_model = Mage::getModel('braintree/paymentmethod');
$_loggedIn = Mage::app()->isInstalled() && Mage::getSingleton('customer/session')->isLoggedIn();
$_storedCards = $_model->currentCustomerStoredCards();
$_useVault = $_loggedIn && $_model->useVault() && count($_storedCards);
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" name="payment[cc_last4]" id="<?php echo $_code ?>_cc_last4" value="" />
    <?php if ($_useVault): ?>
        <li id="<?php echo $_code ?>_token_selector">
            <label for="<?php echo $_code ?>_cc_token"><?php echo $this->__('Payment Information') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_token" name="payment[cc_token]">
                    <?php foreach ($_storedCards as $creditCard): ?>
                        <option value="<?php echo $creditCard->token?>">
                            <?php echo $creditCard->maskedNumber ?>
                        </option>
                    <?php endforeach; ?>
                        <option value=''><?php echo $this->__('Add new card') ?></option>
                </select>
            </div>
        </li>
    <?php endif; ?>
    <li class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" data-encrypted-name="payment[cc_number]"  title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry validate-cc-number validate-digits" value="" />
        </div>
    </li>
    <li class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li class="hide_if_token_selected">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>"  class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" data-encrypted-name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <?php if ($this->hasSsCardType()): ?>
    <li id="<?php echo $_code ?>_cc_type_ss_div" class="hide_if_token_selected">
        <ul class="inner-form">
            <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
            <li>
                <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                <span class="input-box">
                    <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                </span>
            </li>

            <li>
                <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                        <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <li class="adv-container">&nbsp;</li>
        </ul>
    </li>
    <?php endif; ?>

    <?php if($_loggedIn && $_model->useVault()): ?>
        <li id="<?php echo $_code ?>_store_in_vault_div" style="text-align:left;<?php echo ($_loggedIn) ? '' : 'display:none;' ?>" class="hide_if_token_selected">
            <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>" class="input-checkbox" id="<?php echo $_code ?>_store_in_vault" name="payment[store_in_vault]" value="1" />
            <label for="<?php echo $_code ?>_store_in_vault" class="required" style="float:none;"><?php echo $this->__('Save this card for future use') ?></label>
        </li>
    <?php endif; ?>
</ul>

<script type="text/javascript">
//<![CDATA[
(function() {

<?php if ($_useVault): ?>
    var selectBox = $('<?php echo $_code ?>_cc_token');
    var initToken = selectBox.getValue();

    if (initToken)
    {
        $('<?php echo $_code ?>_cc_last4').value = selectBox[selectBox.selectedIndex].text.slice(-4);
        $('<?php echo $_code ?>_cc_type').value = "";
        $$('.hide_if_token_selected').invoke('hide');
    }

    $('<?php echo $_code ?>_cc_token').observe('change', function (e) {
        var selectBox = $(this);
        var token = selectBox.getValue();

        if (token)
        {
            $('<?php echo $_code ?>_cc_last4').value = selectBox[selectBox.selectedIndex].text.slice(-4);
            $('<?php echo $_code ?>_cc_type').value = "";
            $$('.hide_if_token_selected').invoke('hide');
        }
        else
        {
            $$('.hide_if_token_selected').invoke('show');

        }
    });
<?php endif ?>

$('<?php echo $_code ?>_cc_number').observe('change', function(){
    $('<?php echo $_code ?>_cc_last4').value = $("<?php echo $_code ?>_cc_number").value.slice(-4);
});

var braintree = Braintree.create('<?php echo $_model->getConfigData('client_side_encryption_key') ?>');

var keepFieldEncryptedWithHidden = function(input, hidden) {
    var encryptField = function() {
        var text = input.value;
        var encrypted = braintree.encrypt(text);
        hidden.value = encrypted;
    };
    input.observe("change", encryptField);
    setTimeout(encryptField, 300);
};

var createElement = function(tagName, attrs) {
    var element, attr, value;

    element = document.createElement(tagName);

    for (attr in attrs) {
        if (attrs.hasOwnProperty(attr)) {
            value = attrs[attr];
            element.setAttribute(attr, value);
        }
    }

    return element;
};

var keepFieldEncrypted = function(input) {
    if (!input) return;
    var fieldName = input.getAttribute("data-encrypted-name");
    var hidden = createElement("input", {
        type: "hidden",
        name: fieldName,
        value: ""
    });
    input.parentNode.appendChild(hidden);
    keepFieldEncryptedWithHidden(input, hidden);
};

keepFieldEncrypted($("<?php echo $_code ?>_cc_number"));
keepFieldEncrypted($("<?php echo $_code ?>_cc_cid"));


var loggedIn = <?php echo ($_loggedIn) ? 'true' : 'false' ?>;
if ($$('#onestepcheckout-form').first() && !loggedIn)
{
    $('id_create_account').observe('change', function() {
        $('<?php echo $_code ?>_store_in_vault_div').toggle();
    });
}
else if ($('co-payment-form'))
{
    $$('.encrypted-field').each(function(element){
        element.remove();
    });
}

})();
//]]></script>
