<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $_category = $this->getCategory();
?>

<?php if ($_category): ?>
<!--	<div class="panel panel-default">-->
<!--		<div class="panel-heading">-->
<!--			<h3 class="panel-title">--><?php //echo $this->escapeHtml($_category->getName()) ?><!--</h3>-->
<!--		</div>-->
<!--		--><?php //if ($description = $_category->getDescription()): ?>
<!--			<div class="panel-body">-->
<!--				--><?php //echo $description ?>
<!--			</div>-->
<!--		--><?php //endif; ?>
<!---->
<!--	</div>-->


	<?php if ($postList = trim($this->getPostListHtml())): ?>
		<?php echo $postList ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There are no posts matching your selection.') ?>
	<?php endif; ?>
<?php endif; ?>