<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php
$post = $this->getPost();
$author = $post->getAuthor();


//var_dump($author);

// determine if in contributors category
$_url = $post->getPermalink();
$_url_standard = $post->getPermalink();
$_contributors = false;
if ( in_array(7,$post->getCategoryIds()))
{
	$_url .= 'all';
	$_contributors = true;
	$comments = $post->getComments();
}
else
{
	$authorAvatar = $post->getAuthorAvatarUrl(50, $author->getUserEmail());
}


// check to see if in contributor articles, if so, do not show any from contributors
$urlString = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($urlString);
if (strpos($url->getPath(),'im-listening/contributors') == 1 )
{
	if ( in_array(7,$post->getCategoryIds()) && strpos($url->getPath(),'all') > 1 )
	{
		// lets hide the article
		return;
	}
}

?>

<div class="panel panel-default">



	<div class="panel-body">

		<?php

		if ( !$_contributors )
		{
		?>
		<div class="wordpress-header">
			<div class="date-wrapper">
				<span class="date-day">
					<?php
					echo date('d', strtotime($post->getPostDateRaw()));
					?>
				</span>
				<span class="date-month-year">
					<?php
					echo date('M Y', strtotime($post->getPostDateRaw()));
					?>
				</span>
			</div>
			<div class="title-wrapper">

				<a class="h2-wordpress" href="<?php echo $_url ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
					<h2><?php echo $this->escapeHtml($post->getPostTitle()) ?></h2>
				</a>


					<div class="wordpress-contributor-wrapper">


						<?php //echo $post->getAuthor()->getContributorImage(); ?>

						<div class="contributor-wrapper">

							<?php
							if ( $post->getAuthor()->getContributorImage() != '' )
							{

							?>
							<img src="<?php echo $post->getAuthor()->getContributorImage(); ?>">
							<?php
							}
							?>
							<a href="<?php echo Mage::getBaseUrl().'im-listening/contributors/'. $post->getAuthor()->getUserNicename(); ?>/all">
								<?php echo $post->getAuthor()->getDisplayName(); ?>
								<span>View My Articles</span>
							</a>

						</div>



					</div>




				<div class="addthis_sharing_toolbox"></div>

				<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53a3aa090df647cf"></script>

			</div>



		</div>

		<?php
		}
		else {
			?>
			<div class="wordpress-header contributers-list">
				<div class="title-wrapper">

					<a class="h2-wordpress" href="<?php echo $_url ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
						<h2><?php echo $this->escapeHtml($post->getPostTitle()) ?></h2>
					</a>
				</div>
			</div>
			<div class="contributer-actions">
				<a href="<?php echo $_url; ?>" class="">View all my articles</a> |
				<a href="<?php echo $_url_standard; ?>" class="comments-link">View Comments <span class="badge badge-gray"><?php echo $post->getCommentCount(); ?></span></a>
			</div>

		<?php
		}

		?>


		<?php echo $this->getBeforePostContentHtml() ?>
		<div class="post-entry entry<?php if ($post->getFeaturedImage): ?> post-entry-with-image<?php endif; ?>">

			<?php if ($post->isViewableForVisitor()): ?>
				<?php if ($featuredImage = $post->getFeaturedImage()): ?>
					<div class="featured-image left">
						<a href="<?php echo $_url ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
					</div>
				<?php endif; ?>
				<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
					<?php echo $post->getPostExcerpt( true, true) ?>
				<?php else: ?>
					<?php echo $post->getPostContent() ?>
				<?php endif; ?>



				<?php




				echo $this->getCommentsHtml()

				?>

			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml($post) ?>
			<?php endif; ?>
		</div>
	</div>
</div>

