<?php

$letters = range('A', 'Z');

?>

	<ul class="pagination products-listing">
		<?php
		foreach ($letters AS $let)
		{

			if ( in_array($let, $activeAlpha))
			{
				?>
				<li class='<?php if ($query == $let) { echo 'active'; }	?>'>
					<a href='<?php echo $this->getSiteUrl()."?q=".$let; ?>'>
						<?php echo $let; ?>
					</a>
				</li>
			<?php
			}
			else
			{
				?>
				<li>
					<a class='disabled'>
						<?php echo $let; ?>
					</a>
				</li>
			<?php
			}
		}

		?>
		<li <?php
		if ($query == 'ALL')
		{
			echo 'class="active"';
		}
		?>>
			<a href="<?php echo $this->getSiteUrl()."?q=all";?>">
				Show All
			</a>
		</li>
	</ul>



<?php


if ( count($data) )
{
	foreach ( $data AS $category )
	{
		$collection = Mage::getModel('catalog/product')
			->getCollection()
			->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
			->addAttributeToSelect('*')
			->addAttributeToFilter('category_id', ['in' => [$category->getId()]]);

		if (count($collection))
		{
		?>

		<div class="box-account box-account-padding">

				<h3 class="float-left ingredients-header">
					<?php echo $category->getName(); ?>

					<div class="ingredient-info"><span class="information">Information</span> <span class="caret"></span>
						<div class="ingredient-links"><?php
							echo $category->getMediaLinks();
							?>
						</div>
					</div>

				</h3>




			<div class="box-content productsearch">
		<?php


		foreach ( $collection AS $d )
		{
			?>
			<div class="media">

				<table>
					<tr>

						<td class="product-list-image">
							<a href="<?php echo $d->getProductUrl(); ?>">
								<img class="media-object" src="<?php echo $this->helper('catalog/image')->init($d, 'image')->resize(120, 120) ?>" alt="<?php echo $d->getNameFrontend() ?: $d->getName();?>">
							</a>
						</td>

						<td class="product-list-details">
							<a href="<?php echo $d->getProductUrl(); ?>">
								<h4 class="media-heading"><?php echo $d->getNameFrontend() ?: $d->getName();?></h4>
							</a>
							<div class="media-description">
								<?php echo $d->getShortDescription();?>
							</div>
						</td>

						<td class="product-list-price">
							<?php
							$product_block = new Mage_Catalog_Block_Product;
							?>
							<?php echo $product_block->getPriceHtml($d); ?>

							<button class="btn btn-cart btn-sm" type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($d); ?>')">
								<i class="fa fa-plus"></i> <?php echo $this->__('Add to Cart') ?>
							</button>
							<a href="<?php echo $d->getProductUrl(); ?>" class="btn btn-info btn-sm">
								Learn More
							</a>
							<?php
							unset($product_block);
							?>
						</td>

					</tr>


				</table>

				<div class="clearfix"></div>

			</div>
			<hr />
		<?php

		}
		?>
			</div>
		</div>

	<?php
		}
	}

}
else
{
	?><div class="alert alert-warning">There are no products that match.</div><?php
}

?>